Repository kaihodev/hikidashi, pull requests merged in 2021-04, with the labels that each got.

#1 Develop
  .gitignore
  esbuild.config.js
  esbuild.test.config.js
  package.json
  src/safe/add.ts
  src/safe/subtract.ts
  src/shared/generics.d.ts
  src/tests/benches/add.ts
  src/tests/benches/subtract.ts
  src/tests/util.ts
  src/unsafe/add.ts
  src/unsafe/subtract.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#5 make docs
  docs/.gitignore
  docs/babel.config.js
  docs/docs/installation.md
  docs/docs/safe/functions/add.md
  docs/docs/safe/functions/divide.md
  docs/docs/safe/functions/modulo.md
  docs/docs/safe/functions/multiply.md
  docs/docs/safe/functions/remainder.md
  docs/docs/safe/functions/subtract.md
  docs/docs/safe/index.md
  docs/docs/safe/modules.md
  docs/docs/unsafe/functions/add.md
  docs/docs/unsafe/functions/divide.md
  docs/docs/unsafe/functions/modulo.md
  docs/docs/unsafe/functions/multiply.md
  docs/docs/unsafe/functions/remainder.md
  docs/docs/unsafe/functions/subtract.md
  docs/docs/unsafe/index.md
  docs/docs/unsafe/modules.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/sidebars/safe-sidebar.js
  docs/sidebars/unsafe-sidebar.js
  docs/src/components/HomepageFeatures.js
  docs/src/components/HomepageFeatures.module.css
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/index.module.css
  docs/static/.nojekyll
  docs/static/img/abstract.svg
  docs/static/img/easy.svg
  docs/static/img/fast.svg
  docs/static/img/favicon.ico
  docs/static/img/hikidashi.png
  docs/static/img/modular.svg
  docs/yarn.lock
  safe.md
  unsafe.md
Labels: documentation

#6 Create Unit Tests (jest)
  jest.config.ts
  package.json
  src/tests/src/safe/add.test.ts
  src/tests/src/safe/divide.test.ts
  src/tests/src/safe/modulo.test.ts
  src/tests/src/safe/multiply.test.ts
  src/tests/src/safe/remainder.test.ts
  src/tests/src/safe/subtract.test.ts
  src/tests/src/unsafe/add.test.ts
  src/tests/src/unsafe/divide.test.ts
  src/tests/src/unsafe/modulo.test.ts
  src/tests/src/unsafe/multiply.test.ts
  src/tests/src/unsafe/remainder.test.ts
  src/tests/src/unsafe/subtract.test.ts
Labels: enhancement

#8 Update .npmignore
  .npmignore
Labels: enhancement, good first issue

#7 Conform to directory standard
  .gitignore
  .npmignore
  esbuild.config.js
  package.json
  src/index.ts
  src/tests/src/safe/math/add.test.ts
  src/tests/src/safe/math/divide.test.ts
  src/tests/src/safe/math/modulo.test.ts
  src/tests/src/safe/math/multiply.test.ts
  src/tests/src/safe/math/remainder.test.ts
  src/tests/src/safe/math/subtract.test.ts
  src/tests/src/unsafe/math/add.test.ts
  src/tests/src/unsafe/math/divide.test.ts
  src/tests/src/unsafe/math/modulo.test.ts
  src/tests/src/unsafe/math/multiply.test.ts
  src/tests/src/unsafe/math/remainder.test.ts
  src/tests/src/unsafe/math/subtract.test.ts
  yarn.lock
Labels: enhancement

#12 rename
  package.json
  run-all-benchmarks.sh
Labels: enhancement

#14 feat: husky
  .husky/pre-commit
  .lintstagedrc.json
  .npmignore
Labels: enhancement

#15 Documentation gh-page
  .github/workflows/cd-docs.yml
  docs/docs/installation.md
  docs/docs/safe/functions/add.md
  docs/docs/safe/functions/divide.md
  docs/docs/safe/functions/identity.md
  docs/docs/safe/functions/map.md
  docs/docs/safe/functions/mapip.md
  docs/docs/safe/functions/modulo.md
  docs/docs/safe/functions/multiply.md
  docs/docs/safe/functions/noop.md
  docs/docs/safe/functions/remainder.md
  docs/docs/safe/functions/subtract.md
  docs/docs/safe/modules.md
  docs/docs/unsafe/functions/add.md
  docs/docs/unsafe/functions/divide.md
  docs/docs/unsafe/functions/identity.md
  docs/docs/unsafe/functions/map.md
  docs/docs/unsafe/functions/mapip.md
  docs/docs/unsafe/functions/modulo.md
  docs/docs/unsafe/functions/multiply.md
  docs/docs/unsafe/functions/noop.md
  docs/docs/unsafe/functions/remainder.md
  docs/docs/unsafe/functions/subtract.md
  docs/docs/unsafe/modules.md
  docs/docusaurus.config.js
  docs/sidebars/safe-sidebar.js
  docs/sidebars/unsafe-sidebar.js
  docs/src/pages/index.js
Labels: documentation

#17 Add Typescript
  docs/package.json
  docs/yarn.lock
Labels: documentation

#18 docs
  docs/docs/safe/functions/add.md
  docs/docs/safe/functions/divide.md
  docs/docs/safe/functions/identity.md
  docs/docs/safe/functions/map.md
  docs/docs/safe/functions/mapip.md
  docs/docs/safe/functions/modulo.md
  docs/docs/safe/functions/multiply.md
  docs/docs/safe/functions/noop.md
  docs/docs/safe/functions/remainder.md
  docs/docs/safe/functions/subtract.md
  docs/docs/unsafe/functions/add.md
  docs/docs/unsafe/functions/divide.md
  docs/docs/unsafe/functions/identity.md
  docs/docs/unsafe/functions/map.md
  docs/docs/unsafe/functions/mapip.md
  docs/docs/unsafe/functions/modulo.md
  docs/docs/unsafe/functions/multiply.md
  docs/docs/unsafe/functions/noop.md
  docs/docs/unsafe/functions/remainder.md
  docs/docs/unsafe/functions/subtract.md
Labels: documentation

#20 Use github secrets for actions
  .github/workflows/cd-docs.yml
Labels: documentation

#21 Populate un/safe.md and CI Test
  .github/workflows/cd-docs.yml
  .github/workflows/ci-test.yml
  safe.md
  unsafe.md
Labels: documentation

#25 feat: pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#27 added border radius to logo on docs
  docs/src/css/custom.css
Labels: documentation

#29 refactor: scripts & ci
  .github/workflows/cd-docs.yml
  .github/workflows/ci-test.yml
  package.json
Labels: enhancement

#31 docs: create getting-started with readme contents
  docs/docs/getting-started.md
  docs/docs/installation.md
  docs/docs/safe/functions/add.md
  docs/docs/safe/functions/divide.md
  docs/docs/safe/functions/each.md
  docs/docs/safe/functions/filter.md
  docs/docs/safe/functions/identity.md
  docs/docs/safe/functions/map.md
  docs/docs/safe/functions/mapip.md
  docs/docs/safe/functions/modulo.md
  docs/docs/safe/functions/multiply.md
  docs/docs/safe/functions/noop.md
  docs/docs/safe/functions/remainder.md
  docs/docs/safe/functions/subtract.md
  docs/docs/safe/index.md
  docs/docs/safe/modules.md
  docs/docs/unsafe/functions/add.md
  docs/docs/unsafe/functions/divide.md
  docs/docs/unsafe/functions/each.md
  docs/docs/unsafe/functions/filter.md
  docs/docs/unsafe/functions/identity.md
  docs/docs/unsafe/functions/map.md
  docs/docs/unsafe/functions/mapip.md
  docs/docs/unsafe/functions/modulo.md
  docs/docs/unsafe/functions/multiply.md
  docs/docs/unsafe/functions/noop.md
  docs/docs/unsafe/functions/remainder.md
  docs/docs/unsafe/functions/subtract.md
  docs/docs/unsafe/index.md
  docs/docs/unsafe/modules.md
  docs/package.json
  docs/sidebars.js
  docs/sidebars/safe-sidebar.js
  docs/sidebars/unsafe-sidebar.js
  docs/src/pages/index.js
Labels: documentation

#33 feat: emit declarations
  .github/workflows/cd-docs.yml
  .github/workflows/ci-codeql.yml
  jest.config.ts
  package.json
  src/tsconfig.json
  tests/tsconfig.json
  tsconfig.json
Labels: documentation

#34 feat(config): add scope-enum
  commitlint.config.js
Labels: documentation, enhancement
