Repository kaihodev/hikidashi, pull requests merged in 2022-10, with the labels that each got.

#77 docs: rollback CI node version
  .github/workflows/cd-docs.yml
Labels: documentation

#75 fix(tests): use arr size 1000 instead of 100
  benchmarks/array/map.ts
Labels: bugfix

#76 feat(unsafe): add maddeq
  src/unsafe/matrix/maddeq.ts
Labels: enhancement

#78 feat(unsafe): add msubeq
  src/unsafe/matrix/msubeq.ts
Labels: enhancement

#80 chore(docs): bump lockfile
  docs/yarn.lock
Labels: dependencies

#82 chore(docs): bump deps in package.json
  docs/package.json
  docs/yarn.lock
Labels: dependencies
